### PR TITLE
Add FreeBSD platform support

### PR DESCRIPTION
**Pull request by olevole**
#### Pull Request (PR) description
Add FreeBSD platform support

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Awesome work @olevole 

This needs FreeBSD added to the `metadata.json` file which should trigger it being added to the tests. It should also be added to the README under Limitations.

https://github.com/voxpupuli/puppet-telegraf#limitations

**Comment by olevole** [comment]
@ghoneycutt done

**Comment by ghoneycutt** [comment]
Ugh, the spec tests on travis do not show the actual tests. Ran locally and it seems that `on_supported_os()` in the spec tests is not testing against FreeBSD. @alexjfisher @bastelfreak any ideas?

**Comment by olevole** [comment]
it seems that TravisCI still does not support FreeBSD

**Comment by smortex** [comment]
<details>
<summary>Note</summary>

Using the [documentation formatter](https://relishapp.com/rspec/rspec-core/docs/command-line/format-option#documentation-format) in the CI test suite output would help in figuring out which tests are run and not run.
</details>

`on_supported_systems` loads facts from the targetted systems and exercise the classes, so no matter what is the OS running the code: FreeBSD facts can be used to run the code on a Linux host.

The problem here seems to be that `on_supported_os` expect a precise version of the facts (`facterversion: '3.6'`), but facterdb does not have FreeBSD facts for this version:
https://github.com/camptocamp/facterdb/tree/master/facts/3.6

**Comment by ghoneycutt** [comment]
@olevole Perhaps try not specifying the facterversion at https://github.com/voxpupuli/puppet-telegraf/blob/master/spec/classes/telegraf_spec.rb#L4

or specifying a version that has freebsd facts.

facterdb is poorly documented and I don't have much experience with using it from spec tests. :(

**Comment by olevole** [comment]
> facterdb is poorly documented and I don't have much experience with using it from spec tests. :(

Yes, I experience the same problems..

I tried to use get_facts.sh scipt from facterdb and get on FreeBSD12/FreeBSD13:
```
% grep -R facterversion /vagrant/*
/vagrant/1.6/freebsd-13-x86_64.facts:  "facterversion": "1.6.18",
/vagrant/1.7/freebsd-13-x86_64.facts:  "facterversion": "1.7.6",
/vagrant/2.0/freebsd-13-x86_64.facts:  "facterversion": "2.0.2",
/vagrant/2.1/freebsd-13-x86_64.facts:  "facterversion": "2.1.0",
/vagrant/2.2/freebsd-13-x86_64.facts:  "facterversion": "2.2.0",
/vagrant/2.3/freebsd-13-x86_64.facts:  "facterversion": "2.3.0",
/vagrant/2.4/freebsd-13-x86_64.facts:  "facterversion": "2.4.6",
/vagrant/2.5/freebsd-13-x86_64.facts:  "facterversion": "2.5.1",
/vagrant/3.14/freebsd-13-amd64.facts:  "facterversion": "3.14.1",
```

I assume **3.14.1** is an acceptable version.

**Comment by bastelfreak** [comment]
Hi,
I'm going to close this PR due to inactivity. Please reopen and rebase it if you're still interested in it.

**Pull request closed without merging**
