### PR TITLE
Fix: input/output files are missing correct permissions

### PR DESCRIPTION
**Pull request by punycode**
Since some input plugins contain sensitive data (like credentials),
they should also be protected by stricter file permissions.

### CODE REVIEW

**Comment by nrdmn** [comment]
I think we should have stricter permissions on all telegraf configuration files. Output configuration may contain credentials, too, and to a user of this puppet module it is not obvious which files are protected and which are not, so telegraf.conf should have the same permissions.

**Comment by punycode** [comment]
It already has, as far as i can see, since I copied the permission settings from `telegraf::config`.

**Comment by punycode** [comment]
I think the `0640` mode together with the `telegraf:telegraf` default ownership is the most reasonable default for this.

So I would say: We're good here.

**Comment by nrdmn** [comment]
You're right about telegraf.conf's permissions, but no permissions are being set in output.pp.

**Comment by punycode** [comment]
Ah, sorry. I missed that one, since I originally came across that problem with tag `1.4.0` (which had no `telegraf::output`). Give me a second, will amend…

**Comment by yankcrime** [comment]
If you want to fix the merge conflicts and incorporate the suggestions made by @thias in #69 then this is good to go.

**Comment by punycode** [comment]
Rebased against current `master` and incorporated the changes suggested by @thias in #69.

**Comment by bastelfreak** [comment]
Hi,
I'm going to close this PR due to inactivity. Please reopen and rebase it if you're still interested in it.

**Pull request closed without merging**
