### PR TITLE
change key id to new pub key

### LINKED ISSUE #167: NO_PUBKEY on Ubuntu | Key has changed
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Any
- Ruby: Any
- Distribution: Debian / Ubuntu
- Module version: 1.5.0

## How to reproduce (e.g Puppet code you use)
Apply Module to an Ubuntu 20.04 LTS node.

## What are you seeing
Public Key not available for the repository.

## What behaviour did you expect instead
The pubkey being available.

## Output log
```
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 684A14CF2582E0C5
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Reading package lists...
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: GPG error: https://repos.influxdata.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 684A14CF2582E0C5
```

## Any additional information you'd like to impart
Seems the key has changed today. On the repos.influxdata.com site, the old key is now "influxdb.key.old".

### PR DESCRIPTION
**Pull request by theo-meow**
#### Pull Request (PR) description
Change default key ID to the new influxdata public key.

#### This Pull Request (PR) fixes the following issues
Fixes #167

### CODE REVIEW

**Review by kuldazbraslav — APPROVED** [review]

**Comment by theo-meow** [comment]
On further investigation it seems that some packages are still signed with the old key. However, behavior is inconsistent on my end. Can anyone confirm?

**Comment by kuldazbraslav** [comment]
I can confirm that telegraf does not install with this module - neither with the old nor the new key. It seems to me like a problem on Influx's side.

I managed to fix the behaviour by adding the old key above the `apt::source` you updated:

```
        apt::key { 'influxdb.key.old':
          id     => '05CE15085FC09D18E99EFB22684A14CF2582E0C5',
          source => "${telegraf::repo_location}influxdb.key.old",
        }
```

**Comment by theo-meow** [comment]
Yeah I did this as well in the oldkey branch on my fork. I wasn't sure if this is right however... And if it is, it seems like something that is about to get fixed / changed in a few days time.

**Comment by raiford** [comment]
I opened a support ticket with InfluxData about this and it looks like they lagged on actually re-signing their repos with the new key they published.  It appears that they have re-signed the repos now with the new key.

**Comment by raiford** [comment]
Nevermind.  Looks like they now reverted everything back to the old key.

**Comment by theo-meow** [comment]
guess this PR is no longer needed then?

**Pull request closed without merging**
